name: drive_or_drunk_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_ui_auth: ^1.7.0
  firebase_ui_oauth_google: ^1.2.0
  cloud_firestore: ^5.6.4
  shared_preferences: ^2.3.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
