name: drive_or_drunk_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_ui_auth: ^1.7.0
  firebase_ui_oauth_google: ^1.2.0
  cloud_firestore: ^5.6.4
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  flex_color_scheme: ^8.1.1
  flutter_native_splash: ^2.4.4
  carousel_slider: ^5.0.0
  google_sign_in: ^6.3.0
  flutter_svg: ^2.0.17
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  flutter_typeahead: ^5.2.0
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  http: ^1.4.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/logo_android12.png
    - assets/homepage_img.png
    - assets/homepage_img2.png
    - assets/events/event1.png
    - assets/events/event2.png
    - assets/events/event3.png
    - assets/icons/google_logo.svg
    - assets/logos/logo_test.png
